# -*- coding: utf-8 -*-
"""text-image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxVadVh2YZgv7JYhwHIJNA6ICuNijEbx
"""

!pip install diffusers transformers accelerate safetensors gradio --upgrade

import torch
from diffusers import StableDiffusionPipeline
from huggingface_hub import login
import gradio as gr

from huggingface_hub import login
login("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") # my token here

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True
).to("cuda")

def generate_image(prompt):
    try:
        image = pipe(prompt).images[0]
        return image
    except Exception as e:
        return f"Error: {str(e)}"

gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(label="Enter your prompt", placeholder="A futuristic city at sunset..."),
    outputs=gr.Image(type="pil", label="Generated Image"),
    title="🎨 Stable Diffusion Image Generator",
    description="Enter a creative prompt to generate an image using Stable Diffusion v1.5.",
    theme="soft",
    allow_flagging="never"
).launch()